### ISSUE TITLE
Harbor Tab not displaying correctly

### ISSUE THREAD

**Issue by mattSSB** [container-registry/backstage-plugin-harbor#266]
Hi there,

I am attempting to add the Harbor plugin using this guide [here](https://github.com/container-registry/backstage-plugin-harbor/blob/master/README.md). I have enabled the Frontend and Backend as instructed but the plugin is not working as intended. 

My plugin configuration in the app-config.yaml includes the following structure:

```
harbor:
  baseUrl: https://harbor.domain.com
  username:
    $env: HARBOR_USERNAME
  password:
    $env: HARBOR_PASSWORD
```

My annotations are setup as follows, where my-project and my-repo are the same value:
```
goharbor.io/repository-slug: harbor.domain.com/my-project/my-repo
```

In my Dev environment I am seeing the following issue:
![image](https://github.com/container-registry/backstage-plugin-harbor/assets/157729901/25256e8e-7b39-4698-b43a-7cb524e5bbd4)

With the error:
![image](https://github.com/container-registry/backstage-plugin-harbor/assets/157729901/9e07a3e7-7bd7-4543-995c-51caf4f49c3f)

Any help resolving this issue would be greatly appreciated.
